### ISSUE TITLE
Generer des tuiles ? 

### ISSUE THREAD

**Issue by philae-ael** [Holosmos/PetaRabbit#4]
Il faudrait pouvoir générer des tuiles sur le tas, afin de pouvoir les servir afin de pouvoir visionner des images tel que dans dans un viewer Leaflet. (tel que fait [ici](https://github.com/naegi/Mandelbrot))

Dans Leaflet, une tuile est défini par 
- un zoom
- un offset en X
- un offset en Y

## Propriétés de ces valeurs
- Les offsets sont toujours comprises entre 0 et 2^n  - 1 avec n le niveau de zoom.
- Les offsets x (réciproquement y) et x + 1 (y + 1) ne doivent avoir un bord commun (mais pas de pixel en commun = pas de zone en double)
- Le zoom est compris entre 0 et une valeur arbitraire que l'on choisit (il suffit de mettre un grand niveau de zoom max, pour ne plus en avoir peur)

==> Tout ce fait lors de la conversion en zoom/x/y (cf ce que je fais [ici](https://github.com/naegi/Mandelbrot/blob/5e3d7ecdab133f9c53e8b25acb82ab218643f100/src/utils.c#L7))

## Autre
La taille des images doit être constante (carré?), Google Maps utilise des tuiles de 256x256

**Comment by Holosmos** [comment]
Ok faudra mettre les bornes formules pour le offset, mais a priori il n'y a rien de difficile.

On peut spécifier facilement le zoom (que j'appelle echelle), l'origine (qui devra être calculée par les offset donnés) et la taille de l'image.

Je m'y penche demain, mais tu seras probablement plus rapide ...

**Comment by philae-ael** [comment]
Oh j'aurais fini ce soir, je finit juste de documenter mon algo sur mon dépot pour mandelbrot et je copie-colle vers ici

**Comment by philae-ael** [comment]
J'y arrive pas vraiment, le code est assez peu maintenable en l'état, y trop de variables qui se promènent et de bouts de codes dispatchés par ci, par là, en l'état, le code n'est plus utilisable pour qqun qui n'a pas touché au code avant (et difficilement par moi)

**Comment by Holosmos** [comment]
Le code de ton algo ?

**Comment by philae-ael** [comment]
Non mon algo fait 5 lignes :-p , je parle de petarabbit en général

TIps: Les références, c'est bien, mais en interne, ce que ça fait, c'est que ça transfert un pointeur vers la donnée, et donc tu ne gagnes rien quand tu as un char, int, float, double (à vérifier pour ces deux là)... C'est surtout utile quand tu as de grandes quantités de données à transférer (vector, arrays...), ou la majorité des classes

**Comment by Holosmos** [comment]
Bah dis moi ce que tu veux pour le code, mais en l'état tout est rassemblé dans Parametres.h et utilisé dans le début du main. Je vois difficilement ce qu'on peut faire de plus simple ...

**Comment by philae-ael** [comment]
Prenons par exemple, pour l'échelle, où est ce que tu calcules ça ? [Ici (tu l'initialise)](https://github.com/Holosmos/PetaRabbit/blob/master/main.cpp#L38), [là](https://github.com/Holosmos/PetaRabbit/blob/master/Dynamicien.cpp#L135), [là aussi](https://github.com/Holosmos/PetaRabbit/blob/master/Dynamicien.cpp#L112)... Ça commence à être pas mal étalé ! 

Ce qu'il faudrait par exemple, ce serait avoir une seule fonction où tout est calculé, oui, c'est une toute petite perte de perf, que l'on peut facilement compenser en l'encapsulant dans une classe, ou avec une lambda, et là tu as quasiment perdu ta perte de perf, gagné en lisibilité et en maintenabilité !

Ou encore, ton parametres.h contient énormément de variable, je veux ajuster le programme, je modifie quoi ? Tu pourrais créer une classe Fractale, avec chacun des paramètre un minimum documenté, et ensuite tu hérites, ou crée des instances de cette classe que tu vas personnaliser, en disant par exemple, je veux algo, avec tel paramètres de départ... Afin de bien cloisonner, d'encapsuler

En gros, faut que tu te demandes, qui doit faire quoi ? 

Ma fractale doit elle connaitre sa taille en pixel ? Non je ne pense pas, elle doit avoir en entrée un range du points, qui forme un rectangle, par exemple de -2.5 - 1i à 0 + 1i et retourner une liste de résultats

Fin ce sont juste des exemples, franchement je ne sais pas à quoi devrait ressembler le code, mais bon on est à 8 cpp pour calculer un ensemble de Julia, et il en reste à optimiser (bien que les maths, ça aide beaucoup)

**Comment by Holosmos** [comment]
Bah dans le cas de l'echelle, elle a une valeur initiale et peut être modifiée avec l'interface SFML. C'est donc normal qu'elle ne soit pas fixe.

D'ailleurs tes deux derniers liens ne sont pas des initialisations de l'echelles, je comprends pas bien ce que tu veux dire.


Si tu veux ajuster le programme, tout se fait dans Parametre.h. Tu n'as rien d'autre à toucher.
Toutes les valeurs initiales sont données là dedans. Et si elles sont reprises dans main.cpp c'est parce qu'elles peuvent être modifiées par l'interface SFML, c'est la seule raison.


D'ailleurs, tout est déjà plus ou moins encapsulé au maximum. Les paramètres qui te sembleraient obscurs dans Parametre.h sont des paramètres fins de comportement, qui n'ont pas vocation à être fixés dans les classes mais manipulés.


Je documenterai plus demain. Mais honnêtement, il te suffit de passer un peu de temps à lire Parametre.h (sans la partie dédiée à Cycles) et comment il est utilisé dans le main.cpp et tu verras qu'il n'y a rien de superflu.

> Ma fractale doit elle connaitre sa taille en pixel ? Non je ne pense pas, elle doit avoir en entrée un range du points, qui forme un rectangle, par exemple de -2.5 - 1i à 0 + 1i et retourner une liste de résultats

À aucun moment ça n'arrive. Les classes sont gérées selon les axes que j'ai présentés dans le topic de présentation, et c'est totalement respecté.

Les structures Julia, Mandelbrot ignorent totalement de la nature du pixel, elles ne connaissent que le point complexe qu'il représente.

> mais bon on est à 8 cpp pour calculer un ensemble de Julia, et il en reste à optimiser (bien que les maths, ça aide beaucoup)

Le niveau du premier axe est optimisé sur les maths. Sur le code il y a peut-être encore des progrès à faire, mais j'y crois assez peu.

C'est normal d'avoir un aussi grand nombre de choses en jeu. Le projet n'est pas destiné à ne servir qu'un seul ensemble de Julia. Il a vocation à faire des dynamiques très différentes. À vrai dire, il a vocation à traiter toutes les dynamiques discrètes.

**Comment by philae-ael** [comment]
Bon demain, je comiterais si j'ai le temps des petits trucs de factorisation de code pour te montrer ce que je veux dire, mais c'est pas sûr vu qu'il qu'il faut que je me remette à bosser pour la Fac (et pas de l'info, c'est pas ma branche du tout)

**Comment by Holosmos** [comment]
J'ai quasiment tout en place. Il n'y a que les offset qui me cassent la tête ...

On est d'accord que ça va de 0 à 2^(zoom)-1 ? Et que ça va de gauche à droite et de haut en bas ?

J'ai fait une nouvelle branche si tu as le coeur pour check le main ...

**Comment by philae-ael** [comment]
Ouip 
Sur ce que j'ai fait, pour un niveau de zoom de 1:
- x=0 y=0 => coin en haut à gauche
- x=0 y=1 => coin en bas à gauche
- x=1 y=0 => coin en haut à droite
- x=1 y=1 => coin en bas à droite

**Comment by Holosmos** [comment]
Je viens de comprendre ce que j'avais pas compris, je vais tenter de faire ça demain

**Comment by Holosmos** [comment]
Tout est en place dans la branche "Tuiles"
